import { Project, ServiceDetail } from './types';

export const LOCALIZED_DATA = {
  vi: {
    nav: {
      home: 'Trang chủ',
      services: 'Dịch vụ',
      whyUs: 'Tại sao chọn chúng tôi',
      projects: 'Dự án',
      contact: 'Liên hệ',
      getQuote: 'Yêu Cầu Báo Giá',
    },
    hero: {
      badge: 'ENGINEERING EXCELLENCE',
      title: 'Định nghĩa Lại Tương lai Qua',
      titleAccent: 'Phần Mềm Tùy Chỉnh.',
      subtitle: 'Chúng tôi cung cấp các giải pháp công nghệ tiên tiến từ App, Web Design đến SEO chuyên sâu và Hệ thống AI tự động hóa.',
      btnStart: 'Bắt Đầu Ngay',
      btnServices: 'Xem Dịch Vụ',
      qualityCommitment: '100% CAM KẾT CHẤT LƯỢNG',
    },
    aboutCompact: {
      title: 'Sức Mạnh Từ Một Chuyên Gia',
      desc: 'Quang Minh Group không chỉ là một đơn vị công nghệ; chúng tôi là đối tác chiến lược vận hành bởi tư duy tinh gọn. Với tâm thế của một "one-member tech powerhouse", chúng tôi tập trung tối đa vào chất lượng kỹ thuật, loại bỏ các rào cản hành chính để mang đến sản phẩm nhanh hơn, thông minh hơn và hiệu quả hơn.',
    },
    servicesCompact: {
      title: 'Dịch Vụ Chuyên Sâu',
      subtitle: 'Giải pháp công nghệ toàn diện cho doanh nghiệp hiện đại.',
      cards: [
        {
          id: 's_app',
          title: 'Phát Triển Ứng Dụng',
          desc: 'Xây dựng ứng dụng di động native và cross-platform (iOS/Android) với trải nghiệm mượt mà và hiệu năng tối ưu.',
          linkText: 'Tìm hiểu thêm',
        },
        {
          id: 's_web',
          title: 'Thiết Kế Web',
          desc: 'Website chuẩn UI/UX, tối ưu chuyển đổi và tốc độ tải trang cực nhanh.',
          tag: 'LEGACY READY',
          isDark: true,
        },
        {
          id: 's_seo',
          title: 'SEO Chuyên Sâu',
          desc: 'Đưa doanh nghiệp của bạn lên trang đầu kết quả tìm kiếm với chiến lược content và technical SEO bền vững.',
        },
        {
          id: 's_ai',
          title: 'AI Chatbots',
          desc: 'Tích hợp trí tuệ nhân tạo để tự động hóa quy trình chăm sóc khách hàng 24/7.',
        },
        {
          id: 's_auto',
          title: 'Automation Tools',
          desc: 'Công cụ tự động hóa tùy chỉnh giúp tiết kiệm hàng trăm giờ làm việc thủ công mỗi tháng.',
        },
      ],
    },
    whyUsSection: {
      title: 'Tại Sao Chọn',
      titleAccent: 'Quang Minh Group?',
      description: 'Chúng tôi không chỉ viết code, chúng tôi xây dựng nền tảng cho sự tăng trưởng của bạn.',
      reasons: [
        {
          id: 'r1',
          title: 'Tốc Độ Phản Hồi',
          desc: 'Mô hình làm việc trực tiếp giúp giải quyết vấn đề ngay lập tức mà không qua các tầng trung gian.',
        },
        {
          id: 'r2',
          title: 'Kỹ Thuật Bậc Thầy',
          desc: 'Mọi dòng code đều được tối ưu hóa cho bảo mật, mở rộng và hiệu năng cao nhất.',
        },
        {
          id: 'r3',
          title: 'Đổi Mới Liên Tục',
          desc: 'Luôn cập nhật những công nghệ AI và framework mới nhất để mang lại lợi thế cạnh tranh.',
        },
      ],
      stats: [
        { value: '99%', label: 'Uptime Guaranteed' },
        { value: '24/7', label: 'Monitoring & Support' },
        { value: '150+', label: 'Projects Delivered' },
        { value: '10x', label: 'Faster Deployment' },
      ],
    },
    servicesPage: {
      badge: 'DỊCH VỤ CỦA CHÚNG TÔI',
      title: 'Giải pháp công nghệ',
      titleAccent: 'đột phá',
      titleSuffix: ' cho doanh nghiệp.',
      subtitle: 'Chúng tôi kết hợp tư duy thiết kế sáng tạo với năng lực kỹ thuật chuyên sâu để xây dựng những sản phẩm số vượt trội, giúp doanh nghiệp tối ưu quy trình và tăng trưởng bền vững.',
      ctas: {
        title: 'Sẵn sàng để bắt đầu dự án của bạn?',
        desc: 'Hãy liên hệ với đội ngũ chuyên gia của Quang Minh Group để nhận được sự tư vấn chuyên sâu và báo giá chi tiết nhất cho ý tưởng của bạn.',
        btnContact: 'Liên hệ tư vấn ngay',
        btnPricing: 'Xem bảng giá dịch vụ',
      },
    },
    projectsPage: {
      badge: 'DANH MỤC DỰ ÁN',
      title: 'Kiến tạo trải nghiệm số',
      titleAccent: 'đẳng cấp',
      subtitle: 'Khám phá cách chúng tôi giúp các đối tác toàn cầu chuyển đổi số thành công bằng công nghệ tiên tiến và thiết kế tinh tế.',
      filterAll: 'Tất cả',
      ctaTitle: 'Bạn có ý tưởng tuyệt vời?',
      ctaDesc: 'Hãy để chúng tôi giúp bạn hiện thực hóa nó bằng công nghệ đỉnh cao và thiết kế sáng tạo.',
      ctaBtn: 'BẮT ĐẦU DỰ ÁN NGAY',
    },
    contactPage: {
      title: 'Hãy Bắt Đầu Dự Án',
      titleSuffix: 'Của Bạn.',
      subtitle: 'Sẵn sàng để đưa ý tưởng của bạn thành hiện thực? Hãy để lại thông tin, chúng tôi sẽ liên hệ tư vấn giải pháp tối ưu nhất trong vòng 24h.',
      emailLabel: 'Email',
      phoneLabel: 'Điện thoại',
      addressLabel: 'Địa chỉ',
      followUs: 'THEO DÕI CHÚNG TÔI',
      form: {
        name: 'HỌ TÊN',
        namePlaceholder: 'Nguyễn Văn A',
        email: 'EMAIL',
        emailPlaceholder: 'example@gmail.com',
        service: 'DỊCH VỤ QUAN TÂM',
        serviceChoose: 'Chọn dịch vụ...',
        serviceOptions: [
          'Phát triển ứng dụng di động',
          'Thiết kế & Phát triển Website',
          'Thương mại điện tử chuyên sâu',
          'Tích hợp Hệ thống AI / Chatbot',
          'Hệ thống Tự động hóa & Khác',
        ],
        message: 'LỜI NHẮN',
        messagePlaceholder: 'Mô tả ngắn gọn yêu cầu của bạn...',
        btnSubmit: 'Gửi Yêu Cầu Tư Vấn',
        success: 'Yêu cầu của bạn đã được gửi thành công! Chúng tôi sẽ liên hệ trong vòng 24 giờ.',
        disclaimer: 'Bằng cách gửi form này, bạn đồng ý với Chính sách bảo mật của chúng tôi.',
      },
    },
    footer: {
      about: 'Chuyên gia phát triển phần mềm tùy chỉnh, AI và SEO. Mang đến giải pháp kỹ thuật vượt trội cho doanh nghiệp.',
      quickLinks: 'Quick Links',
      language: 'Language',
      vietnamese: 'Tiếng Việt',
      english: 'English',
      copyright: '© 2026 Quang Minh Group. Engineering Excellence in Custom Software.',
    },
    quoteEstimator: {
      title: 'Bảng Ước Tính Chi Phí Dự Án',
      subtitle: 'Trả lời nhanh 4 câu hỏi để nhận báo giá sơ bộ ngay lập tức.',
      step1: '1. Loại hình dự án của bạn là gì?',
      step2: '2. Quy mô & Độ phức tạp dự án?',
      step3: '3. Bạn cần triển khai trong bao lâu?',
      step4: '4. Thông tin liên hệ của bạn',
      prev: 'Quay lại',
      next: 'Tiếp tục',
      submit: 'Nhận Báo Giá Ngay',
      complexity: {
        basic: 'Cơ bản / MVP (Ít tính năng, giao diện đơn giản)',
        medium: 'Trung bình (Đầy đủ tính năng cốt lõi, tích hợp API)',
        advanced: 'Nâng cao / Enterprise (Hệ thống lớn, bảo mật cao, tải trọng lớn)',
      },
      timeline: {
        fast: 'Gấp (Dưới 1 tháng)',
        normal: 'Bình thường (1 - 3 tháng)',
        flex: 'Thoải mái (Trên 3 tháng)',
      },
      resultTitle: 'Báo Giá Ước Tính',
      resultDesc: 'Dựa trên lựa chọn của bạn, mức giá đầu tư sơ bộ dao động khoảng:',
      resultCall: 'Gửi báo giá chính thức qua Email',
    },
  },
  en: {
    nav: {
      home: 'Home',
      services: 'Services',
      whyUs: 'Why Us',
      projects: 'Projects',
      contact: 'Contact',
      getQuote: 'Get a Quote',
    },
    hero: {
      badge: 'ENGINEERING EXCELLENCE',
      title: 'Defining the Future Through',
      titleAccent: 'Custom Software.',
      subtitle: 'We provide cutting-edge technological solutions spanning Mobile Apps, custom Web Design, specialized SEO, and automated AI Systems.',
      btnStart: 'Get Started',
      btnServices: 'Our Services',
      qualityCommitment: '100% QUALITY COMMITMENT',
    },
    aboutCompact: {
      title: 'The Power of Focused Expertise',
      desc: 'Quang Minh Group is not just a technology provider; we are a strategic partner operated under a lean philosophy. With the mindset of a "one-member tech powerhouse", we maximize engineering quality and eliminate administrative friction to deliver faster, smarter, and more impactful software products.',
    },
    servicesCompact: {
      title: 'Specialized Services',
      subtitle: 'Comprehensive tech solutions built for modern businesses.',
      cards: [
        {
          id: 's_app',
          title: 'Application Development',
          desc: 'Building high-performance native and cross-platform mobile apps (iOS & Android) with flawless interactions.',
          linkText: 'Learn more',
        },
        {
          id: 's_web',
          title: 'Web Design',
          desc: 'High-conversion, UI/UX optimized websites featuring blazing-fast loading speeds.',
          tag: 'LEGACY READY',
          isDark: true,
        },
        {
          id: 's_seo',
          title: 'Specialized SEO',
          desc: 'Secure top search engine rankings through sustainable content and technical SEO architecture.',
        },
        {
          id: 's_ai',
          title: 'AI Chatbots',
          desc: 'Integrate bespoke conversational AI tools to automate customer operations on a 24/7 basis.',
        },
        {
          id: 's_auto',
          title: 'Automation Tools',
          desc: 'Engineered automatic workflows saving businesses hundreds of manual labor hours every month.',
        },
      ],
    },
    whyUsSection: {
      title: 'Why Choose',
      titleAccent: 'Quang Minh Group?',
      description: 'We do not just write code, we build the digital foundation for your long-term success.',
      reasons: [
        {
          id: 'r1',
          title: 'Responsive Turnaround',
          desc: 'Direct-to-expert collaboration loops ensure swift problem-solving without bureaucratic layers.',
        },
        {
          id: 'r2',
          title: 'Masterful Engineering',
          desc: 'Every file and system block is fully optimized for top security standards, easy scale, and peak speeds.',
        },
        {
          id: 'r3',
          title: 'Continuous Innovation',
          desc: 'Constantly deploying modern AI systems and progressive web tech Stack to secure your market advantage.',
        },
      ],
      stats: [
        { value: '99%', label: 'Uptime Guaranteed' },
        { value: '24/7', label: 'Monitoring & Support' },
        { value: '150+', label: 'Projects Delivered' },
        { value: '10x', label: 'Faster Deployment' },
      ],
    },
    servicesPage: {
      badge: 'OUR SERVICES',
      title: 'Breakthrough technology',
      titleAccent: 'solutions',
      titleSuffix: ' for enterprise success.',
      subtitle: 'We blend creative design thinking with deep-domain technical capabilities to develop outstanding digital solutions, optimizing business operations and driving sustainable growth.',
      ctas: {
        title: 'Ready to launch your project?',
        desc: 'Connect with our elite product experts today to retrieve deep consulting and a formal technical blueprint for your ideas.',
        btnContact: 'Consult our expert now',
        btnPricing: 'View service pricing plans',
      },
    },
    projectsPage: {
      badge: 'PROJECT PORTFOLIO',
      title: 'Crafting premium digital',
      titleAccent: 'experiences',
      subtitle: 'Discover how we empower global partners to thrive in digital transformation via progressive architectural design.',
      filterAll: 'All',
      ctaTitle: 'Have a brilliant concept?',
      ctaDesc: 'Let us help you bring it to life using state-of-the-art software systems and creative layout designs.',
      ctaBtn: 'START YOUR PROJECT NOW',
    },
    contactPage: {
      title: 'Start Your Project',
      titleSuffix: 'Today.',
      subtitle: 'Ready to translate your ideas into robust software realities? Leave your contact details; our engineer response SLA is within 24h.',
      emailLabel: 'Email Us',
      phoneLabel: 'Call Us',
      addressLabel: 'Our Office',
      followUs: 'FOLLOW US',
      form: {
        name: 'FULL NAME',
        namePlaceholder: 'John Doe',
        email: 'EMAIL ADDRESS',
        emailPlaceholder: 'example@gmail.com',
        service: 'SERVICE OF INTEREST',
        serviceChoose: 'Choose a service...',
        serviceOptions: [
          'Mobile App Development',
          'Website Design & Custom Frontend',
          'Premium E-Commerce Systems',
          'AI / Chatbot System Integration',
          'Custom Workflow Automation Tools',
        ],
        message: 'DETAILED MESSAGE',
        messagePlaceholder: 'Briefly layout your project scope...',
        btnSubmit: 'Send Request Details',
        success: 'Your request was dispatched successfully! Our product architect will touch base within 24 hours.',
        disclaimer: 'By submitting this request, you agree to our Privacy Terms.',
      },
    },
    footer: {
      about: 'Specialists in customized suite software, automated conversational AI, and technical SEO. We commit to bringing stellar technical outcomes for global ventures.',
      quickLinks: 'Quick Links',
      language: 'Language',
      vietnamese: 'Tiếng Việt',
      english: 'English',
      copyright: '© 2024 Quang Minh Group. Engineering Excellence in Custom Software.',
    },
    quoteEstimator: {
      title: 'Project Cost Estimator',
      subtitle: 'Answer 4 quick questions to receive a preliminary investment quote instantly.',
      step1: '1. What type of project is it?',
      step2: '2. Project Scale & Complexity?',
      step3: '3. What is your ideal timeframe?',
      step4: '4. Your Contact Details',
      prev: 'Previous',
      next: 'Continue',
      submit: 'Calculate Instantly',
      complexity: {
        basic: 'Basic / MVP (Few main screens, clean structure)',
        medium: 'Medium (Core services, complex dashboard integration)',
        advanced: 'Advanced / Enterprise (Heavy load infrastructure, microservices, maximum security)',
      },
      timeline: {
        fast: 'Expedited (Under 1 month)',
        normal: 'Standard (1 - 3 months)',
        flex: 'Flexible (More than 3 months)',
      },
      resultTitle: 'Estimated Budget',
      resultDesc: 'Based on your selected specifications, the initial investment is approximated at:',
      resultCall: 'Email Me the Official Estimation',
    },
  },
};

export const PROJECTS_LIST: Project[] = [
  {
    id: 'p1',
    title: 'Hệ thống quản lý giáo dục - EduNext',
    category: 'Quản lý (SaaS)',
    categoryKey: 'saas',
    description: 'Hệ thống quản lý toàn diện trường học và các trung tâm đào tạo, đồng bộ hóa học sinh, giáo viên, học liệu và thanh toán hóa đơn tự động.',
    image: '/src/assets/images/edu_dashboard_1779681168197.png',
    tags: ['Next.js', 'PostgreSQL', 'Tailwind', 'Docker'],
    specs: 'Management System',
  },
  {
    id: 'p2',
    title: 'App đặt lịch Spa - GlowWell',
    category: 'Ứng dụng di động',
    categoryKey: 'mobile',
    description: 'Ứng dụng di động giúp người dùng tìm kiếm, chọn lịch hẹn, thanh toán và gửi đánh giá khách quan về chất lượng chăm sóc sắc đẹp spa.',
    image: '/src/assets/images/glow_well_1779681185315.png',
    tags: ['React Native', 'Expo', 'FastAPI', 'Redis'],
    specs: 'Mobile Application',
  },
  {
    id: 'p3',
    title: 'Ví điện tử thông minh - ZenPay',
    category: 'Fintech',
    categoryKey: 'fintech',
    description: 'Ứng dụng ví tài chính thế hệ mới với các biểu đồ trực quan, tích hợp AI tư vấn chi tiêu và tối ưu hóa phí giao dịch tức thì.',
    image: '/src/assets/images/zen_pay_1779681203205.png',
    tags: ['iOS/Android', 'Node.js', 'Web3', 'MongoDB'],
    specs: 'Fintech Wallet',
  },
  {
    id: 'p4',
    title: 'Thời trang cao cấp - Aura',
    category: 'E-commerce',
    categoryKey: 'ecommerce',
    description: 'Nền tảng thương mại điện tử chuyên biệt hiển thị các dòng thời trang xa xỉ, đồng hồ cao cấp với tích hợp AR thử đồ ảo.',
    image: '/src/assets/images/aura_ecommerce_1779681226465.png',
    tags: ['React', 'NestJS', 'Stripe API', 'GraphQL'],
    specs: 'E-commerce System',
  },
];

export const CORE_SERVICES: ServiceDetail[] = [
  {
    id: 'ser1',
    num: '01',
    title: 'Thiết kế UI/UX',
    description: 'Chúng tôi tập trung vào trải nghiệm người dùng cuối, tạo ra những giao diện không chỉ đẹp mắt mà còn tối ưu hóa hành trình khách hàng, tăng tỷ lệ chuyển đổi.',
    bullets: [
      'Nghiên cứu người dùng (UX Research)',
      'Thiết kế tương tác (Interaction Design)',
      'Prototyping & Testing',
      'Hệ thống thiết kế (Design Systems)',
    ],
    ctaText: 'Tìm hiểu thêm',
  },
  {
    id: 'ser2',
    num: '02',
    title: 'Phát triển Website',
    description: 'Xây dựng hệ thống Frontend & Backend mạnh mẽ, bảo mật cao và dễ dàng mở rộng theo quy mô doanh nghiệp.',
    bullets: [
      'Frontend: React, Next.js, Vue',
      'Backend: Node.js, NestJS, Go',
      'Cloud: AWS, GCP, Cloudflare',
    ],
    ctaText: 'Tìm hiểu thêm',
    tags: ['React/Next.js', 'Node.js', 'TypeScript'],
    isDark: true,
  },
  {
    id: 'ser3',
    num: '03',
    title: 'Thương mại điện tử',
    description: 'Giải pháp bán hàng trực tuyến toàn diện, từ quản lý kho bãi đến tích hợp thanh toán quốc tế và nội địa.',
    bullets: [
      'Custom Shopify Development',
      'Tích hợp Stripe/MoMo',
    ],
    ctaText: 'Xem giải pháp',
  },
  {
    id: 'ser4',
    num: '04',
    title: 'Bảo trì & Vận hành',
    description: 'Đảm bảo hệ thống luôn hoạt động 24/7 với hiệu suất cao nhất và an toàn tuyệt đối.',
    bullets: [
      'Giám sát hệ thống 24/7/365',
      'Tối ưu hóa tốc độ load & SEO',
      'Sửa lỗi & Phát hành phiên bản mới',
    ],
    ctaText: 'Liên hệ bảo trì',
  },
];

export const QUOTE_PRICE_CONFIG = {
  usdToVnd: 25400,
  basePriceUsd: {
    web: 2200,
    app: 2800,
    ecommerce: 2600,
    ai: 3200,
    automation: 1800,
  },
  complexityMultiplier: {
    basic: 0.6,
    medium: 1,
    advanced: 1.6,
  },
  timelineMultiplier: {
    fast: 1.2,
    normal: 1,
    flex: 0.85,
  },
  range: {
    min: 0.9,
    max: 1.12,
  },
} as const;
